version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_inst
    ports:
      - 5432
    environment:
      POSTGRES_DB: securegate
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker_inst
    ports:
      - 8000
      - 8001
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    restart: unless-stopped
    network_mode: bridge