[tool.black] # Black code formatter
line-length = 100
target-version = ['py310', 'py311']

[tool.pylint."messages control"] # Pylint
ignore = ["__init__.py"]
disable = "all"
enable = [
    "empty-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring"
]

[tool.isort] # Isort import sorter
profile = "black"

[tool.pyright] # Pyright static type checker
venvPath = "./"
venv = ".venv"
include = ["apps", "packages", "libs"]
reportMissingTypeArgument = true  # Report generic classes used without type arguments
strictListInference = true  # Use union types when inferring types of lists elements, instead of Any