[tool.black] # Black code formatter
line-length = 100
target-version = ['py310', 'py311']

[tool.pylint."messages control"] # Pylint
ignore = ["__init__.py"]
disable = "all"
enable = [
    "empty-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring"
]

[tool.isort] # Isort import sorter
profile = "black"
line_length = 100
