[tool.black]
line-length = 100
target-version = ['py310', 'py311']

[tool.pylint."messages control"]
ignore = ["__init__.py"]
disable = "all"
enable = [
    "empty-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring"
]

[tool.isort]
profile = "black"