#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[1;32m'
CYAN='\033[1;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "${GREEN}Running pre-commit hooks...${NC}"

echo "${YELLOW}1. Running javascript pre-commit hooks...${NC}"
npm run pre-commit

echo "${CYAN}2. Running python pre-commit hooks...${NC}"
pre-commit run